package cn.itsoha.entity;

import java.io.Serializable;

public class Order implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column o_order.oid
     *
     * @mbg.generated Fri Sep 21 10:59:55 CST 2018
     */
    private String oid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column o_order.o_name
     *
     * @mbg.generated Fri Sep 21 10:59:55 CST 2018
     */
    private String oName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column o_order.o_address
     *
     * @mbg.generated Fri Sep 21 10:59:55 CST 2018
     */
    private String oAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column o_order.o_desc
     *
     * @mbg.generated Fri Sep 21 10:59:55 CST 2018
     */
    private String oDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column o_order.o_time
     *
     * @mbg.generated Fri Sep 21 10:59:55 CST 2018
     */
    private String oTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column o_order.o_user
     *
     * @mbg.generated Fri Sep 21 10:59:55 CST 2018
     */
    private String oUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column o_order.o_phone
     *
     * @mbg.generated Fri Sep 21 10:59:55 CST 2018
     */
    private String oPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column o_order.o_tag
     *
     * @mbg.generated Fri Sep 21 10:59:55 CST 2018
     */
    private Integer oTag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column o_order.o_downorder_time
     *
     * @mbg.generated Fri Sep 21 10:59:55 CST 2018
     */
    private String oDownorderTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column o_order.o_receoder_time
     *
     * @mbg.generated Fri Sep 21 10:59:55 CST 2018
     */
    private String oReceoderTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column o_order.o_okoder_time
     *
     * @mbg.generated Fri Sep 21 10:59:55 CST 2018
     */
    private String oOkoderTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table o_order
     *
     * @mbg.generated Fri Sep 21 10:59:55 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column o_order.oid
     *
     * @return the value of o_order.oid
     *
     * @mbg.generated Fri Sep 21 10:59:55 CST 2018
     */
    public String getOid() {
        return oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column o_order.oid
     *
     * @param oid the value for o_order.oid
     *
     * @mbg.generated Fri Sep 21 10:59:55 CST 2018
     */
    public void setOid(String oid) {
        this.oid = oid == null ? null : oid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column o_order.o_name
     *
     * @return the value of o_order.o_name
     *
     * @mbg.generated Fri Sep 21 10:59:55 CST 2018
     */
    public String getoName() {
        return oName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column o_order.o_name
     *
     * @param oName the value for o_order.o_name
     *
     * @mbg.generated Fri Sep 21 10:59:55 CST 2018
     */
    public void setoName(String oName) {
        this.oName = oName == null ? null : oName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column o_order.o_address
     *
     * @return the value of o_order.o_address
     *
     * @mbg.generated Fri Sep 21 10:59:55 CST 2018
     */
    public String getoAddress() {
        return oAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column o_order.o_address
     *
     * @param oAddress the value for o_order.o_address
     *
     * @mbg.generated Fri Sep 21 10:59:55 CST 2018
     */
    public void setoAddress(String oAddress) {
        this.oAddress = oAddress == null ? null : oAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column o_order.o_desc
     *
     * @return the value of o_order.o_desc
     *
     * @mbg.generated Fri Sep 21 10:59:55 CST 2018
     */
    public String getoDesc() {
        return oDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column o_order.o_desc
     *
     * @param oDesc the value for o_order.o_desc
     *
     * @mbg.generated Fri Sep 21 10:59:55 CST 2018
     */
    public void setoDesc(String oDesc) {
        this.oDesc = oDesc == null ? null : oDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column o_order.o_time
     *
     * @return the value of o_order.o_time
     *
     * @mbg.generated Fri Sep 21 10:59:55 CST 2018
     */
    public String getoTime() {
        return oTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column o_order.o_time
     *
     * @param oTime the value for o_order.o_time
     *
     * @mbg.generated Fri Sep 21 10:59:55 CST 2018
     */
    public void setoTime(String oTime) {
        this.oTime = oTime == null ? null : oTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column o_order.o_user
     *
     * @return the value of o_order.o_user
     *
     * @mbg.generated Fri Sep 21 10:59:55 CST 2018
     */
    public String getoUser() {
        return oUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column o_order.o_user
     *
     * @param oUser the value for o_order.o_user
     *
     * @mbg.generated Fri Sep 21 10:59:55 CST 2018
     */
    public void setoUser(String oUser) {
        this.oUser = oUser == null ? null : oUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column o_order.o_phone
     *
     * @return the value of o_order.o_phone
     *
     * @mbg.generated Fri Sep 21 10:59:55 CST 2018
     */
    public String getoPhone() {
        return oPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column o_order.o_phone
     *
     * @param oPhone the value for o_order.o_phone
     *
     * @mbg.generated Fri Sep 21 10:59:55 CST 2018
     */
    public void setoPhone(String oPhone) {
        this.oPhone = oPhone == null ? null : oPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column o_order.o_tag
     *
     * @return the value of o_order.o_tag
     *
     * @mbg.generated Fri Sep 21 10:59:55 CST 2018
     */
    public Integer getoTag() {
        return oTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column o_order.o_tag
     *
     * @param oTag the value for o_order.o_tag
     *
     * @mbg.generated Fri Sep 21 10:59:55 CST 2018
     */
    public void setoTag(Integer oTag) {
        this.oTag = oTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column o_order.o_downorder_time
     *
     * @return the value of o_order.o_downorder_time
     *
     * @mbg.generated Fri Sep 21 10:59:55 CST 2018
     */
    public String getoDownorderTime() {
        return oDownorderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column o_order.o_downorder_time
     *
     * @param oDownorderTime the value for o_order.o_downorder_time
     *
     * @mbg.generated Fri Sep 21 10:59:55 CST 2018
     */
    public void setoDownorderTime(String oDownorderTime) {
        this.oDownorderTime = oDownorderTime == null ? null : oDownorderTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column o_order.o_receoder_time
     *
     * @return the value of o_order.o_receoder_time
     *
     * @mbg.generated Fri Sep 21 10:59:55 CST 2018
     */
    public String getoReceoderTime() {
        return oReceoderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column o_order.o_receoder_time
     *
     * @param oReceoderTime the value for o_order.o_receoder_time
     *
     * @mbg.generated Fri Sep 21 10:59:55 CST 2018
     */
    public void setoReceoderTime(String oReceoderTime) {
        this.oReceoderTime = oReceoderTime == null ? null : oReceoderTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column o_order.o_okoder_time
     *
     * @return the value of o_order.o_okoder_time
     *
     * @mbg.generated Fri Sep 21 10:59:55 CST 2018
     */
    public String getoOkoderTime() {
        return oOkoderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column o_order.o_okoder_time
     *
     * @param oOkoderTime the value for o_order.o_okoder_time
     *
     * @mbg.generated Fri Sep 21 10:59:55 CST 2018
     */
    public void setoOkoderTime(String oOkoderTime) {
        this.oOkoderTime = oOkoderTime == null ? null : oOkoderTime.trim();
    }
}