package cn.itsoha.entity;

import java.io.Serializable;

public class User implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_user.uid
     *
     * @mbg.generated Fri Sep 21 10:59:55 CST 2018
     */
    private String uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_user.user
     *
     * @mbg.generated Fri Sep 21 10:59:55 CST 2018
     */
    private String user;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_user.pwd
     *
     * @mbg.generated Fri Sep 21 10:59:55 CST 2018
     */
    private String pwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table u_user
     *
     * @mbg.generated Fri Sep 21 10:59:55 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_user.uid
     *
     * @return the value of u_user.uid
     *
     * @mbg.generated Fri Sep 21 10:59:55 CST 2018
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_user.uid
     *
     * @param uid the value for u_user.uid
     *
     * @mbg.generated Fri Sep 21 10:59:55 CST 2018
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_user.user
     *
     * @return the value of u_user.user
     *
     * @mbg.generated Fri Sep 21 10:59:55 CST 2018
     */
    public String getUser() {
        return user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_user.user
     *
     * @param user the value for u_user.user
     *
     * @mbg.generated Fri Sep 21 10:59:55 CST 2018
     */
    public void setUser(String user) {
        this.user = user == null ? null : user.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_user.pwd
     *
     * @return the value of u_user.pwd
     *
     * @mbg.generated Fri Sep 21 10:59:55 CST 2018
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_user.pwd
     *
     * @param pwd the value for u_user.pwd
     *
     * @mbg.generated Fri Sep 21 10:59:55 CST 2018
     */
    public void setPwd(String pwd) {
        this.pwd = pwd == null ? null : pwd.trim();
    }
}