package cn.itsoha.mapper;

import cn.itsoha.entity.Order;

import java.util.List;

public interface OrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table o_order
     *
     * @mbg.generated Fri Sep 21 10:59:55 CST 2018
     */
    int deleteByPrimaryKey(String oid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table o_order
     *
     * @mbg.generated Fri Sep 21 10:59:55 CST 2018
     */
    int insert(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table o_order
     *
     * @mbg.generated Fri Sep 21 10:59:55 CST 2018
     */
    int insertSelective(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table o_order
     *
     * @mbg.generated Fri Sep 21 10:59:55 CST 2018
     */
    Order selectByPrimaryKey(String oid);

    List<Order> findByTag(Integer tag);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table o_order
     *
     * @mbg.generated Fri Sep 21 10:59:55 CST 2018
     */
    int updateByPrimaryKeySelective(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table o_order
     *
     * @mbg.generated Fri Sep 21 10:59:55 CST 2018
     */
    int updateByPrimaryKey(Order record);
}